# Generated by Django 5.0.13 on 2025-12-04 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id_cajero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turno', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaSuper',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion_categoria', models.TextField()),
                ('pasillo', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_perecedero', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ClienteSuper',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('puntos_fidelidad', models.IntegerField()),
                ('direccion_cliente', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('contacto_persona', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('direccion_proveedor', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoSuper',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('codigo_barras', models.CharField(max_length=50)),
                ('peso_gramos', models.IntegerField()),
                ('tipo_empaque', models.CharField(max_length=50)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_supermercado.categoriasuper')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_supermercado.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='VentaSuper',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado_venta', models.CharField(max_length=50)),
                ('numero_ticket', models.CharField(max_length=50)),
                ('id_cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_supermercado.cajero')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_supermercado.clientesuper')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVentaSuper',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descuento_item', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_supermercado.productosuper')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_supermercado.ventasuper')),
            ],
        ),
    ]
