# Generated by Django 5.0.13 on 2025-12-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_supermercado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesuper',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='clientesuper',
            name='fecha_registro',
            field=models.DateField(verbose_name='Fecha de registro'),
        ),
    ]
